version: '2.1'

services:
  docker-httpc:
    image: docker-httpc:0.1
    build: .
    volumes: 
    - /var/run/docker.sock:/var/run/docker.sock
    - ./certs:/certs
    ports:
      - 8080:8080
      - 8443:8443
    environment: 
      - SESSION_KEY